### ISSUE TITLE
Urdu translations

### ISSUE THREAD

**Issue by itdaniher** [forestcontact/Translations_92#1]
@heyshaheer Thank you for your help! Would you translate the following phrases into Urdu and Hindi?

"How did you discover MobileCoin?"

"What do you like about Signal Messenger?"

"What do you do with your MobileCoins?"

"Can you please send me a photo of a farm animal (goat, cow, duck) with today's date written in the dirt next to it?"

"Please don't curse out the developers!"

**Comment by ghost** [comment]
آپ کو موبائل کوئن کے بارے میں کیسے پتا چلا؟

آپ سگنل میسنجر کے بارے میں کیا پسند کرتے ہیں؟

آپ موبائل کوئن کا کیا استعمال کرتے ہیں؟

کیا آپ مہربانی کر کے کسی پالتو جانور مثلاً بکری، گاۓ یا بطح کے ساتھ نیچے مٹی پر آج کی تاریخ لکھ کر اس کی تصویر  بنا کر بھیج سکتے ہیں؟

مہربانی کر کے ڈویلپرز کے لئے نازیبا الفاظ کا استعمال مت کریں۔

**Comment by ghost** [comment]
Aap ko mobilecoin kay baray may kaisay pata chala?

Aap Signal Messenger kay baray may kia pasand kartay hay?

Aap Mobilecoin ka kia istemal kartay hay?

Kia aap mehrbani kar k kisi janwar maslan bakri,gayen ya murgi kay sath matti par aaj ki tareeh (date) likh kar us ki tasweer bana kar mujay bayj saktay hay?

Mehrbani kar k developers kay baray may na-zaiba alfaz ka istemal mat karain.
